### PR TITLE
Update to newer Python versions

### PR DESCRIPTION
**Pull request by dsuess**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@dsuess do you want to add yourself as a maintainer here?

**Comment by dsuess** [comment]
> @dsuess do you want to add yourself as a maintainer here?

That’ll be great. Thanks @ocefpaf

**Comment by ocefpaf** [comment]
> That’ll be great. Thanks @ocefpaf

We can wait for the bot to answer my request in #26 or you can add our username in the list in this PR.

**Comment by dsuess** [comment]
> We can wait for the bot to answer my request in https://github.com/conda-forge/pyembree-feedstock/issues/26 or you can add our username in the list in this PR.

Just added it to this PR

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
